################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  dashboard: true
  insecure: true
################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    exposedByDefault: false
    swarmMode: false
    watch: true
################################################################
# Traefik Logging
################################################################
log:
  level: INFO

################################################################
# Entrypoint
################################################################
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: :443

################################################################
# Challenge TLS
################################################################
certificatesResolvers:
  myresolver:
    acme:
      email: your-email@example.com
      # Remove for production environement
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      storage: letsencrypt/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web