version: '3.8'

services:
  traefik:
    image: traefik:v2.9.6
    ports:
      # Exposes port 80 for incomming web requests
      - "80:80"
      - "443:443"
    #labels:
      #- "traefik.enable=true"
      #- "traefik.http.routers.traefik.rule=Host(`$TRAEFIK_DNS`)"
      #- "traefik.http.routers.traefik.entrypoints=websecure"
      #- "traefik.http.routers.traefik.service=traefik"
      #- "traefik.http.routers.dolibarr.tls.certresolver=myresolver"
      #- "traefik.http.services.traefik.loadbalancer.server.port=8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app/traefik/conf/traefik.yml:/etc/traefik/traefik.yml
      - ./app/traefik/letsencrypt:/letsencrypt

  mariadb:
    image: mariadb:latest
    hostname: mariadb
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: $MYSQL_DATABASE
    secrets:
      - mysql_root_password   
    volumes:
      - ./dump/in:/docker-entrypoint-initdb.d

  dolibarr:
    image: tuxgasy/dolibarr
    environment:
      DOLI_DB_HOST: $DOLI_DB_HOST
      DOLI_DB_USER: $DOLI_DB_USER
      DOLI_DB_PASSWORD_FILE: /run/secrets/mysql_root_password
      DOLI_DB_NAME: $DOLI_DB_NAME
      DOLI_URL_ROOT: $DOLIBARR_DNS
      PHP_INI_DATE_TIMEZONE: $PHP_INI_DATE_TIMEZONE
      DOLI_INSTALL_AUTO: 0
    secrets:
      - mysql_root_password 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dolibarr.rule=Host(`$DOLIBARR_DNS`)"
      - "traefik.http.routers.dolibarr.entrypoints=websecure"
      - "traefik.http.routers.dolibarr.service=dolibarr"
      - "traefik.http.routers.dolibarr.tls.certresolver=myresolver"
      - "traefik.http.services.dolibarr.loadbalancer.server.port=80"
    volumes:
      - ./documents/in:/var/www/documents

  alpine:
    image: docker-cron
    build: app/docker-cron
    init: true
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: $MYSQL_DATABASE
      DOLI_DB_USER: $DOLI_DB_USER
      DOLI_DB_HOST: $DOLI_DB_HOST
    secrets:
      - mysql_root_password 
    volumes:
      - ./app/docker-cron/crontab:/var/spool/cron/crontabs/root
      - ./dump/out:/tmp/dump/out
      - ./documents/in:/tmp/documents/in
      - ./documents/out:/tmp/documents/out

secrets:
  mysql_root_password:
    external: true